### ISSUE TITLE
Agressive polling causes rate limit hits

### ISSUE THREAD

**Issue by antoineco** [triggermesh/aws-event-sources#139]
All AWS sources poll AWS APIs in a `for` loop, which causes a lot of issues due to rate limiting.

At the very least we should throttle our polling with a [`time.Ticker`](https://golang.org/pkg/time/#Ticker).

**Comment by antoineco** [comment]
Another option would be to offer a `push` mode as opposed to the current `pull` model, and create Lambdas on behalf of the user to forward events to us.

Example
```
[SNS] --- event ---> [Lambda] --> [SNS event source]
```

The cost would increase due to the Lambda calls, but it would enable an actual "event-driven" and more immediate approach. Both modes could coexist and be controlled by a spec attribute.

@sebgoa what do you think?

**Comment by tzununbekov** [comment]
If our sources accept events one at a time, limit polling with ticker may negatively affect performance, especially if events creation rate is higher then tick duration. I'd think about dynamic tick interval so that if there are events coming from the source we don't throttle our requests but if there are none - we start to sleep longer with each empty response, up to say 5 seconds. Wdyt?

Regarding `push` mode, I'm wondering how Lambda would receive events and is there a way for us to copy this behavior. I can take a look at this after we implement simple throttling

**Comment by antoineco** [comment]
> If our sources accept events one at a time, limit polling with ticker may negatively affect performance

Our sources currently don't _accept events_, they are all pull based and work by polling AWS APIs, caching the result, comparing with the last observed batch, and computing new events when things have changed. Those events can be sent in bulk on every ticker period if needed.

The current `for { call_aws() }` approach hammers the API. Not only it will get costly on the long run, but one a rate-limit is applied it affects every else negatively.

> Regarding `push` mode, I'm wondering how Lambda would receive events and is there a way for us to copy this behavior. I can take a look at this after we implement simple throttling

Most AWS services can actually generate events!.. but only to AWS Lambda or SNS 🤡  (vendor lock-in, anyone?). My suggestion is that our event sources hook into those services instead of using the polling approach.

**Comment by tzununbekov** [comment]
> Our sources currently don't accept events, they are all pull based and work by polling AWS APIs

yeah, I meant "_if our sources can ingest a batch data_", otherwise ticker duration will define our sources performance

> My suggestion is that our event sources hook into those services instead of using the polling approach

ok, I'll investigate that

**Comment by antoineco** [comment]
I concur, introducing a period reduces the performance. I'd prefer the push model by far, however we want to implement it.

**Comment by sebgoa** [comment]
in most common cases pull should use an exponential backoff, except is we can do some websocket connection with the service and receive events in real time.

I don't like push because you have to open an endpoint to the public internet and you need to secure it. It becomes an entry door. Hence I usually favor pull method.

That said some sources like SNS cannot be a pull so we will have to handle it indeed like github and gitlab.

Using SNS for all aws sources however would mean that the API keys we get from the user will have enough privileges to configure the services and the SNS.

So would be me doing it :) I would do two things:

* quick stop gap measure on our pull sources with a time interval that increases up to "20s". I would check the rate limiting limits.
* I would implement the SNS source like gitlab and see how to properly secure that webhook.

Then with that experience I would decide if I can use SNS as a proxy for all sources. Could be that it is a mode that we can turn on/off.
