### ISSUE TITLE
the local Docker samples need a K_SINK

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-event-sources#205]
When checking out the SQS documentation and trying to run the container locally, I got a segfault if K_SINK was not defined.

I expected the message to be printed on stdout even without a K_SINK.

I had to run a local event display and specify it as K_SINK for messages to be received and forwarded properly.

```
docker run --net=host --rm -e ARN=arn:aws:sqs:us-east-1:587264368683:triggermesh \
                                                 -e AWS_ACCESS_KEY_ID= \
                                                 -e AWS_SECRET_ACCESS_KEY= \
                                                 -e NAME=testsqs \
                                                 -e NAMESPACE=default \
                                                 -e K_SINK=http://localhost:8080 gcr.io/triggermesh/awssqssource:latest
```

with

```
docker run --net=host --rm gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display:latest
```

**Comment by antoineco** [comment]
You're right, I checked the code and Knative libs do not assert whether or not K_SINK is set (could be that your adapter only ever _responds_ with events instead of _sending_ them to an explicit location).

We need to add that check because our sources can't work without a sink. A sink must be defined in all `AWS...Source` objects, but we don't have that extra validation when running the image directly.
