### ISSUE TITLE
Add manifests in release bundle

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-event-sources#276]
Currently the release contains the binaries but not the manifests you can find in `config` with references to pre-built public images.

We should publish a all in one manifest that people can `kubectl apply`

**Comment by antoineco** [comment]
@sameersbn since we use `docker` (`kaniko` more precisely) and not `ko` to perform image releases (unlike Knative), maybe it would be sufficient to concatenate all manifests from `config/` and perform the necessary string replacements `ko:// -> <actual image>` when we press the release button. WDYT?

**Comment by sameersbn** [comment]
> concatenate all manifests from `config/` and perform the necessary string replacements `ko:// -> <actual image>`

yea, that makes sense

**Comment by sebgoa** [comment]
@sameersbn can we get this done
